### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by mikeshihyaolin** [kirtov/lung_diagnostics#5]
Hi Mr. Kirtov,
I have followed your requirements.txt to install the dependences.
Yet, I got the system error "SystemError: unknown opcode"
The detail errors are as follows:

$ python predict.py --wav ../data/anomalies1.wav 
Traceback (most recent call last):
  File "predict.py", line 48, in <module>
    print("Probability of anomalies:", str(predict(data)*100)[:4] + "%")
  File "predict.py", line 42, in predict
    model = load_model()
  File "predict.py", line 36, in load_model
    model = model_from_json(arch)
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/models.py", line 345, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/layers/__init__.py", line 54, in deserialize
    printable_module_name='layer')
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 139, in deserialize_keras_object
    list(custom_objects.items())))
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/engine/topology.py", line 2497, in from_config
    process_node(layer, node_data)
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/engine/topology.py", line 2456, in process_node
    layer(input_tensors, **kwargs)
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/xxxx/anaconda3/envs/lung/lib/python3.6/site-packages/keras/layers/core.py", line 650, in call
    return self.function(inputs, **arguments)
  File "../rnn_anomalies+noise_cv.py", line 61, in <lambda>
SystemError: unknown 

Could you please help me?

**Comment by omi-akif** [comment]
I too have the same problem. What is the reason behind this issue?
